version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      # доступы к бд
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306" # по порту 9906 открыт доступ к базе контейнера
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db # не запускается поуа не подгрузится дб
    volumes:
      - ./app/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
